## Data source properties
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        generate_statistics: false
        show_sql: false
        format_sql: false
        use_sql_comments: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/storage?createDatabaseIfNotExist=true
    username: root
    password: root

currency:
  uah:
    usd: 0.037
    eur: 0.032
  usd:
    uah: 27.28
    eur: 0.88
  eur:
    uah: 30.83
    usd: 1.13