## Data source properties
spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        generate_statistics: false
        show_sql: false
        format_sql: false
        use_sql_comments: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

app:
  jwt:
    secretKey: JwtSecretKey
    expirationTimeMs: 604800000
  header:
    name: Authorization
    type: "Bearer "

currency:
  uah:
    usd: 0.037
    eur: 0.032
  usd:
    uah: 27.28
    eur: 0.88
  eur:
    uah: 30.83
    usd: 1.13